### ISSUE TITLE
[Feature request] Add option to import/export Payload mapping in a file

### ISSUE THREAD

**Issue by ghost** [stuomas/disorient#1]
Hi!

Take time to re-write all payload mapping (new Windows installation, etc...).
Could be a nice idea to add an backup option to load/save all payload mapping in a file ?

**Comment by stuomas** [comment]
Hi,

Thanks for suggestion! I will take a look at it.

**Comment by stuomas** [comment]
I implemented this feature in 0.4.0 but tested it only very briefly. Let me know if you find any bugs with it.

This was a good idea, it will help also me in development because sometimes I have to clear all the mappings from registry to test something.

**Comment by ghost** [comment]
Wonderfull ! That's work fine.
I've tried to load and backup options, no bug for now.
