### ISSUE TITLE
Changing Display configuration (primary only, secondary only, extend)

### ISSUE THREAD

**Issue by VV-Cephai** [stuomas/disorient#3]
Hi,
this tool seemed to be exactly what I was looking for, but in the end I could not get it to work.
I want to change my display setup triggered by MQTT messages. I want to switch from extending the desktop over two screens to just using one screen an back.
This can be easily done by calling "C:\Windows\System32\DisplaySwitch.exe" with the arguments "/extend", "/external", "/internal" (Windows 10).
But no matter how I tried do enter this executable in disorient 0.4 (quotes, argument via payload, or execution as unknown command in powershell) it never seemed to do anything.
executing "C:\Windows\System32\DisplaySwitch.exe" with the arguments /extend as shortcut works,
executing DisplaySwitch.exe /extend in powershell works,
executing "C:\Program Files\Notepad++\notepad++.exe" with disorient works.

Do you have any idea what might be the issue? 

![Screenshot 2021-02-15 224551](https://user-images.githubusercontent.com/2905571/107996424-a8c87900-6fe0-11eb-8025-b6a54b7073ed.png)
![Screenshot 2021-02-15 224053](https://user-images.githubusercontent.com/2905571/107996427-a9f9a600-6fe0-11eb-9b2e-0d80eca51837.png)

**Comment by stuomas** [comment]
Hi! Sorry for late answer. I can confirm your issue. It might be some kind of Windows permission problem or security feature. You can try to copy DisplaySwitch.exe executable from System32 for example to your desktop, and modify the path in your payload mapping. Let me know if it works for you, at least for me that worked.

Some executables from System32 seem to work just fine, some don't :man_shrugging:

(The argument in your last screenshot is in correct format)

**Comment by stuomas** [comment]
@VV-Cephai I found some more information about this from here https://www.samlogic.net/articles/sysnative-folder-64-bit-windows.htm:

> if a 32-bit application includes the "\System32" folder name in a folder path, the system automatically makes a redirection to the SysWOW64

So when you call `C:\Windows\System32\DisplaySwitch.exe` from Disorient, Windows redirects that to `C:\Windows\SysWOW64\DisplaySwitch.exe` that does not exists.

You can change your path in the argument to `C:\Windows\Sysnative\DisplaySwitch.exe` instead. It is a virtual folder that will make the redirect to correct System32 folder.

**Comment by VV-Cephai** [comment]
Thank you very much for your help. This solved the problem perfectly.
